"""Rebuild the WHU XGBoost visit-order performance curve from the full training set.

This version deliberately avoids the earlier simplified reproduction path. It
uses the complete WHU primary training table, the history-aware feature matrix
generated by ``readmission_history_train.py`` (119 features in the current
pipeline), and the tuned XGBoost parameters saved by that full-cohort run.

Inputs:
  data/private/readmission_output/train_data.csv
  data/private/readmission_output/history_model/history_features.csv
  data/private/readmission_output/history_model/history_model_results.json

Outputs:
  NC_revision/xgboost_visit_order_results/
    visit_order_performance.csv
    visit_order_performance.json
    xgb_visit_order_curve.{png,pdf,svg}
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold

BASE_DIR = Path(__file__).resolve().parent
READMISSION_DIR = BASE_DIR.parent / "data" / "private" / "readmission_output"
TRAIN_CSV = READMISSION_DIR / "train_data.csv"
HISTORY_FEATURES_CSV = READMISSION_DIR / "history_model" / "history_features.csv"
HISTORY_RESULTS_JSON = READMISSION_DIR / "history_model" / "history_model_results.json"
OUT_DIR = BASE_DIR / "xgboost_visit_order_results"
OUT_DIR.mkdir(exist_ok=True)

VISIT_ORDER_THRESHOLDS = [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20]
TARGETS = {
    "target_gap_days": {
        "result_key": "gap_days",
        "label": "Next inter-admission gap",
        "color": "#1F77B4",
    },
    "target_next_los": {
        "result_key": "next_los",
        "label": "Next length of stay",
        "color": "#D62728",
    },
}
N_FOLDS = 5
RANDOM_STATE = 42

# First-version parameters: broad config (gap_cap=30) from broad_config_results.json
# and LOS config from model_comparison.py
FIRST_VERSION_PARAMS: dict[str, dict] = {
    "target_gap_days": {
        "cap": 30,
        "params": {
            "n_estimators": 1500,
            "max_depth": 3,
            "learning_rate": 0.01,
            "subsample": 0.8,
            "colsample_bytree": 0.4,
            "min_child_weight": 30,
            "reg_alpha": 5.0,
            "reg_lambda": 10.0,
            "gamma": 0,
        },
    },
    "target_next_los": {
        "cap": 7,
        "params": {
            "n_estimators": 800,
            "max_depth": 5,
            "learning_rate": 0.005,
            "subsample": 0.8,
            "colsample_bytree": 0.4,
            "min_child_weight": 30,
            "reg_alpha": 0.05,
            "reg_lambda": 1.0,
            "gamma": 1.0,
        },
    },
}


def detect_device() -> str:
    try:
        model = xgb.XGBRegressor(device="cuda", n_estimators=2, verbosity=0)
        model.fit(
            np.random.default_rng(1).normal(size=(20, 4)).astype(np.float32),
            np.random.default_rng(2).normal(size=20).astype(np.float32),
        )
        return "cuda"
    except Exception:
        return "cpu"


def load_inputs() -> tuple[pd.DataFrame, pd.DataFrame]:
    if not TRAIN_CSV.exists():
        raise FileNotFoundError(f"Missing {TRAIN_CSV}; run run_step1.py and run_step2.py first.")
    if not HISTORY_FEATURES_CSV.exists():
        raise FileNotFoundError(
            "Missing history-model feature matrix; run readmission_history_train.py before this script."
        )

    train = pd.read_csv(TRAIN_CSV, low_memory=False)
    features = pd.read_csv(HISTORY_FEATURES_CSV, low_memory=False)
    if len(train) != len(features):
        raise ValueError(f"Row mismatch: train_data={len(train)} vs history_features={len(features)}")

    for col in features.columns:
        features[col] = pd.to_numeric(features[col], errors="coerce")

    return train, features


def make_model_params(raw_params: dict[str, object], device: str) -> dict[str, object]:
    params = dict(raw_params)
    params.update({
        "device": device,
        "objective": "reg:squarederror",
        "tree_method": "hist",
        "verbosity": 0,
        "random_state": RANDOM_STATE,
    })
    return params


def fill_features(features: pd.DataFrame) -> pd.DataFrame:
    filled = features.copy()
    for col in filled.columns:
        median_val = filled[col].median()
        filled[col] = filled[col].fillna(median_val if pd.notna(median_val) else 0.0)
    return filled


def cv_scores(X: np.ndarray, y: np.ndarray, params: dict[str, object]) -> dict[str, object]:
    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
    r2s: list[float] = []
    maes: list[float] = []
    rmses: list[float] = []
    best_iters: list[int | None] = []

    for tr, va in kf.split(X):
        model = xgb.XGBRegressor(**params)
        model.fit(X[tr], y[tr], eval_set=[(X[va], y[va])], verbose=False)
        pred = model.predict(X[va])
        r2s.append(float(r2_score(y[va], pred)))
        maes.append(float(mean_absolute_error(y[va], pred)))
        rmses.append(float(np.sqrt(mean_squared_error(y[va], pred))))
        best_iters.append(getattr(model, "best_iteration", None))

    return {
        "r2_mean": float(np.mean(r2s)),
        "r2_std": float(np.std(r2s, ddof=0)),
        "mae_mean": float(np.mean(maes)),
        "mae_std": float(np.std(maes, ddof=0)),
        "rmse_mean": float(np.mean(rmses)),
        "rmse_std": float(np.std(rmses, ddof=0)),
        "r2_folds": r2s,
        "mae_folds": maes,
        "rmse_folds": rmses,
        "best_iterations": best_iters,
    }


def plot_curve(perf: pd.DataFrame, n_features: int) -> None:
    fig, ax = plt.subplots(figsize=(8.6, 5.0))
    for target, meta in TARGETS.items():
        data = perf[perf["target"] == target].sort_values("visit_order_min")
        ax.errorbar(
            data["visit_order_min"],
            data["r2_mean"],
            yerr=data["r2_std"],
            marker="o",
            lw=1.8,
            capsize=3.5,
            color=str(meta["color"]),
            label=str(meta["label"]),
        )
        for _, row in data.iterrows():
            ax.annotate(
                f"{row['r2_mean']:.2f}\nn={int(row['n']):,}",
                (row["visit_order_min"], row["r2_mean"]),
                textcoords="offset points",
                xytext=(4, 6),
                fontsize=6.8,
                color=str(meta["color"]),
            )

    ax.axhline(0, color="#999999", lw=0.7, ls="--")
    ax.set_xticks(VISIT_ORDER_THRESHOLDS)
    ax.set_xlabel("Minimum visit order retained in evaluation set")
    ax.set_ylabel("Cross-validated R2 (5-fold)")
    ax.set_title(
        "XGBoost visit-order performance, WHU primary cohort\n"
        f"First-version parameters: gap cap = 30 d, LOS cap = 7 d ({n_features} features)",
        fontsize=10.5,
        fontweight="bold",
    )
    ax.grid(axis="y", color="#DDDDDD", lw=0.5, alpha=0.75)
    ax.legend(framealpha=0.94, fontsize=8.5, loc="best")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()

    for ext in ("png", "pdf", "svg"):
        fig.savefig(OUT_DIR / f"xgb_visit_order_curve.{ext}", dpi=300 if ext == "png" else None)
    plt.close(fig)


def main() -> None:
    print("[XGB visit-order v1] Loading WHU training data (first-version parameters)...")
    train, features = load_inputs()
    features_filled = fill_features(features)
    X_all = features_filled.values.astype(np.float32)
    device = detect_device()
    print(f"  train_data rows={len(train):,}; features={X_all.shape[1]}; device={device}")
    print(f"  thresholds={VISIT_ORDER_THRESHOLDS}")
    print(f"  First-version params: gap_cap=30 (n_est=1500/depth=3/lr=0.01), los_cap=7 (n_est=800/depth=5/lr=0.005)")

    rows: list[dict[str, object]] = []
    train_visit_order = pd.to_numeric(train["visit_order"], errors="coerce")
    for target, meta in TARGETS.items():
        fv = FIRST_VERSION_PARAMS[target]
        cap = int(fv["cap"])
        params = make_model_params(fv["params"], device)
        y_all = pd.to_numeric(train[target], errors="coerce").clip(upper=cap)
        for threshold in VISIT_ORDER_THRESHOLDS:
            mask = (train_visit_order >= threshold) & y_all.notna()
            n = int(mask.sum())
            if n < N_FOLDS:
                continue
            X = X_all[mask.to_numpy()]
            y = y_all[mask].to_numpy(dtype=np.float32)
            print(
                f"  fit target={target} visit_order>={threshold:<2d} "
                f"n={n:,} features={X.shape[1]} cap={cap}"
            )
            scores = cv_scores(X, y, params)
            rows.append({
                "target": target,
                "target_label": meta["label"],
                "visit_order_min": threshold,
                "n": n,
                "n_features": int(X.shape[1]),
                "cap": cap,
                **scores,
            })
            print(
                f"    R2={scores['r2_mean']:.4f} +/- {scores['r2_std']:.4f}; "
                f"MAE={scores['mae_mean']:.2f}"
            )

    perf = pd.DataFrame(rows)
    perf.to_csv(OUT_DIR / "visit_order_performance.csv", index=False, encoding="utf-8-sig")
    payload = {
        "source_files": {
            "train_data": str(TRAIN_CSV),
            "history_features": str(HISTORY_FEATURES_CSV),
        },
        "cohort": {
            "training_rows": int(len(train)),
            "feature_rows": int(len(features)),
            "feature_count": int(X_all.shape[1]),
        },
        "device": device,
        "n_folds": N_FOLDS,
        "thresholds": VISIT_ORDER_THRESHOLDS,
        "params": {
            key: {"cap": FIRST_VERSION_PARAMS[key]["cap"], **make_model_params(FIRST_VERSION_PARAMS[key]["params"], device)}
            for key in TARGETS
        },
        "results": rows,
    }
    (OUT_DIR / "visit_order_performance.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8"
    )
    plot_curve(perf, X_all.shape[1])
    print(f"\nWrote {OUT_DIR / 'xgb_visit_order_curve.pdf'}")
    print(perf[["target", "visit_order_min", "n", "r2_mean", "r2_std", "mae_mean", "rmse_mean"]].to_string(index=False))


if __name__ == "__main__":
    main()
